language: node_js
node_js: stable
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai'
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean && hexo g
after_script:
  - set -ev
  - git clone https://${GH_REF} blog
  - cd blog
  - git checkout master
  - git config user.name "tianyaqpzm"
  - git config user.email "tianyaqpzm@163.com"
  - cd ../
  - mv ./blog/.git/ ./public/
  - cd ./public
  - git add .
  - git commit -m 'Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M`'
  - echo ${Travis_Token}
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master
branches:
  only:
    - hexo
env:
  global:
    - GH_REF: github.com/tianyaqpzm/tianyaqpzm.github.io.git
    - secure: 0DVj4oc3TlmkPrqJGa9jKHElh/tO+ccOdvoLxJjqOMEgqqibx/iXNGXxzGpj2+76ZFd/dewI0I34OUm6x1/cUwI0y1QrkcvKbu50BmB2Aqn1mgITUjIzhVcwRFZdfdgwzCq+scgGS/rqs07Q674yJ+yplt0QY30MifVCUnA5WyixB/9/kaBdAHGA24iQuNqvRcYQtVTj3K/Bkpm4TYc/hMOL/xE/HLO0yiN/bS2isPQXJGyMs0T1PboWGWZM/vSGQ3DvMx5zIh51kxrvlYvfjy6DXVDOLXcqpSndfJFBldEvFZUhWRP83XUOQuB01tZAkXjeUTABBMFCCi1xSTkOvQ+m97JTrlmWvHnCndl7lZCyW7iVLZ23F4zxettATaKW6QMwfuz9mtWnVujOFSn7ugxw2cX9bh6kJNKAvlBYoYg4bQmHWa0tsrWOFTzBA0MXmZoAbtqRrYQFE8J8C9Hf2GyXWVqpfCocuUsQ4SWZnazfdmlEX/pc2Fz7clxXQF5loEhc7WYJh0MBc1lw5y/pvQ/BR0BzbUYchUZp5Gj5M7oP1YkRDh0SJUfLGFwfcoSpIqYyZkW9Ws8S/zie2N1pNoRU+XX4F+2GSGE17JzkDtfDiTtoyyWRESlF1iDiCI6MUOFe5L9Por9KCoXwr+YY013QcHx8qS7OK7BkC63zp0w=
