language: node_js
node_js: stable

cache:
  apt: true
  directories:
    - node_modules # 缓存不经常更改的内容

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install
  - npm install -g hexo-cli
  - chmod 600 ~/.ssh
  - openssl aes-256-cbc -K $encrypted_e74dc4b9668f_key -iv $encrypted_e74dc4b9668f_iv
    -in Travis_Token.enc -out ~\/.ssh/Travis_Token -d
    #- openssl aes-256-cbc -K $encrypted_e74dc4b9668f_key -iv $encrypted_e74dc4b9668f_iv
    #  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
    #     - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - set -ev
  - git clone https://${GH_REF} blog
  - cd blog
  - git config user.name "Travis"
  - git config user.email "tianyaqpzm@163.com"
  - git checkout master
  - git add ./public
  - git commit -m 'Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M`'
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master

branches:
  only:
    - hexo # 只检测hexo 分支

env:
  global:
    - GH_REF: github.com/tianyaqpzm/tianyaqpzm.github.io.git
